"""add summary column and chat_messages table

Revision ID: ab9fbd6519a1
Revises: cb52fa15fc6b
Create Date: 2026-09-15 23:17:51.882322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9fbd6519a1'
down_revision: Union[str, None] = 'cb52fa15fc6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_document_id'), 'chat_messages', ['document_id'], unique=False)
    op.add_column('documents', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'summary')
    op.drop_index(op.f('ix_chat_messages_document_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
