"""add processing history and extracted metadata

Revision ID: cb52fa15fc6b
Revises: c6059d4779ea
Create Date: 2026-09-10 17:55:11.752183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM


# revision identifiers, used by Alembic.
revision: str = 'cb52fa15fc6b'
down_revision: Union[str, None] = 'c6059d4779ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: hand-edited — autogenerate emitted the generic sa.Enum(...) here,
    # which does not reliably forward create_type through to the Postgres
    # dialect on every code path (confirmed by testing: it worked via
    # MetaData.create_all() but not via the Table.create(checkfirst=False)
    # path Alembic actually uses). postgresql.ENUM is the dialect-native
    # type where create_type is a first-class, always-honored parameter.
    # Without it, this migration tries to CREATE TYPE document_status again
    # (it already exists — created by the first migration for
    # documents.status) and fails with "type document_status already exists".
    op.create_table('processing_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', PG_ENUM('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', name='document_status', create_type=False), nullable=True),
    sa.Column('to_status', PG_ENUM('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', name='document_status', create_type=False), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_history_document_id'), 'processing_history', ['document_id'], unique=False)
    op.add_column('documents', sa.Column('extracted_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extracted_metadata')
    op.drop_index(op.f('ix_processing_history_document_id'), table_name='processing_history')
    op.drop_table('processing_history')
    # ### end Alembic commands ###
